name: release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Package files
        run: |
          mkdir clash-premium-config-${{ steps.get_version.outputs.VERSION }}
          tar -zcvf clash-premium-config-${{ steps.get_version.outputs.VERSION }}.tar.gz ./config ./README.md
          zip -r clash-premium-config-${{ steps.get_version.outputs.VERSION }}.zip ./config ./README.md

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./clash-premium-config-*
          draft: false
